import unittest

from day07.part1 import get_result_part_1


class TestDay07Part1(unittest.TestCase):

    def test1(self):
        test_data = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."""

        result = get_result_part_1(test_data)

        self.assertEqual(21, result)

    def test2(self):
        test_data = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^...^.....
...............
....^.^....^...
..............."""

        result = get_result_part_1(test_data)

        self.assertEqual(7, result)

    def test3(self):
        test_data = """.S.
...
.^.
...
^..
...
..^
..."""

        result = get_result_part_1(test_data)

        self.assertEqual(3, result)
