import unittest

from day07.part2 import get_result_part_2


class TestDay07Part2(unittest.TestCase):

    def test1(self):
        test_data = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."""

        result = get_result_part_2(test_data)

        self.assertEqual(40, result)

    def test2(self):
        test_data = """.......S.......
...............
.......^.......
..............."""

        result = get_result_part_2(test_data)

        self.assertEqual(2, result)

    def test3(self):
            test_data = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.........
..............."""

            result = get_result_part_2(test_data)

            self.assertEqual(5, result)

    def test4(self):
            test_data = """..S.
....
..^.
....
.^.^
....
^...
...."""

            result = get_result_part_2(test_data)

            self.assertEqual(3, result)

    def test5(self):
        test_data = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
..............."""

        result = get_result_part_2(test_data)

        self.assertEqual(8, result)